In [1]:
import pandas as pd
df_movies = pd.read_csv('movies.csv')
df_ratings = pd.read_csv('ratings.csv')
df_merged = pd.merge(df_movies, df_ratings, on='movieId', how='inner')
df_merged.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [2]:
df = df_merged.pivot_table(index='userId', columns='title', values='rating')
# Keep only movies that had at least 8 ratings
df = df.dropna(thresh=8, axis=1)
df.fillna(0, inplace=True)
df.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),102 Dalmatians (2000),12 Angry Men (1957),12 Years a Slave (2013),...,Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),[REC] (2007),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
df_similarity = df.corr(method='pearson')
#Store the data for later to be used in building the API
df_similarity.to_csv('movie_similarity.csv')
df_similarity.head()

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),102 Dalmatians (2000),12 Angry Men (1957),12 Years a Slave (2013),...,Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),[REC] (2007),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,0.063117,-0.023768,0.143482,0.011998,0.087931,0.224052,-0.018608,0.034223,0.009277,...,0.032470,0.134701,0.153158,0.101301,0.049897,0.003233,-0.017905,0.187953,0.062174,0.353194
(500) Days of Summer (2009),0.063117,1.000000,0.142471,0.273989,0.193960,0.148903,0.142141,0.066567,0.159756,0.135486,...,0.178655,0.068407,0.414585,0.355723,0.252226,0.216007,0.126147,0.053614,0.241092,0.125905
10 Cloverfield Lane (2016),-0.023768,0.142471,1.000000,-0.005799,0.112396,0.006139,-0.016835,-0.017692,0.031704,-0.024275,...,0.099059,-0.023477,0.272347,0.241751,0.195054,0.319371,0.082246,0.177846,0.096638,0.002733
10 Things I Hate About You (1999),0.143482,0.273989,-0.005799,1.000000,0.244670,0.223481,0.211473,0.109729,0.011784,0.091964,...,0.104858,0.132460,0.091853,0.158637,0.281934,0.050031,0.088391,0.121029,0.130813,0.110612
"10,000 BC (2008)",0.011998,0.193960,0.112396,0.244670,1.000000,0.234459,0.119132,0.086195,0.059187,-0.025882,...,0.087592,0.094913,0.184521,0.242299,0.240231,0.094773,0.074425,0.088045,0.203002,0.083518

In [8]:
movieLiked = 'Star Wars: Episode V - The Empire Strikes Back (1980)'
similarityScores = df_similarity[movieLiked]
similarityScores.sort_values(ascending=False)[1:50]

title
Star Wars: Episode IV - A New Hope (1977)                                         0.739568
Star Wars: Episode VI - Return of the Jedi (1983)                                 0.712682
Indiana Jones and the Last Crusade (1989)                                         0.593140
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    0.590630
Terminator, The (1984)                                                            0.555766
Matrix, The (1999)                                                                0.522634
Aliens (1986)                                                                     0.521045
Indiana Jones and the Temple of Doom (1984)                                       0.509658
Back to the Future (1985)                                                         0.509016
Star Wars: Episode I - The Phantom Menace (1999)                                  0.504353
Alien (1979)                                                                      0.496744
Star Wars: Episode III - Revenge of the Sith (2005)                               0.476747
Die Hard (1988)                                                                   0.475609
Total Recall (1990)                                                               0.465457
Princess Bride, The (1987)                                                        0.458100
Fifth Element, The (1997)                                                         0.458034
Ghostbusters (a.k.a. Ghost Busters) (1984)                                        0.455268
Blade Runner (1982)                                                               0.448452
RoboCop (1987)                                                                    0.448138
Monty Python and the Holy Grail (1975)                                            0.445145
E.T. the Extra-Terrestrial (1982)                                                 0.443177
Star Wars: Episode II - Attack of the Clones (2002)                               0.441237
Hunt for Red October, The (1990)                                                  0.429633
Predator (1987)                                                                   0.427749
Saving Private Ryan (1998)                                                        0.426178
Men in Black (a.k.a. MIB) (1997)                                                  0.425769
X-Men (2000)                                                                      0.424539
Back to the Future Part II (1989)                                                 0.423715
Superman (1978)                                                                   0.423348
Terminator 2: Judgment Day (1991)                                                 0.421738
Jaws (1975)                                                                       0.416553
Ferris Bueller's Day Off (1986)                                                   0.413682
Unbreakable (2000)                                                                0.413330
Sixth Sense, The (1999)                                                           0.408860
Abyss, The (1989)                                                                 0.402442
Mars Attacks! (1996)                                                              0.400406
Goldfinger (1964)                                                                 0.397958
Groundhog Day (1993)                                                              0.397064
2001: A Space Odyssey (1968)                                                      0.395360
Godfather, The (1972)                                                             0.394514
Face/Off (1997)                                                                   0.392161
Godfather: Part II, The (1974)                                                    0.389531
Spaceballs (1987)                                                                 0.388824
Planet of the Apes (1968)                                                         0.387388
Reservoir Dogs (1992)                                                             0.387185
Who Framed Roger Rabbit? (1988)                                                   0.386360
Rocky (1976)                                                                      0.385724
Spider-Man (2002)                                                                 0.384707
Lethal Weapon (1987)                                                              0.384445
Name: Star Wars: Episode V - The Empire Strikes Back (1980), dtype: float64